export const ROULETTE_VALUES: [string, string | number][] = [
  ["red", 1],
  ["black", 2],
  ["red", 3],
  ["black", 4],
  ["red", 5],
  ["black", 6],
  ["red", 7],
  ["black", 8],
  ["red", 9],
  ["black", 10],
  ["red", 11],
  ["black", 12],
  ["red", 13],
  ["black", 14],
  ["red", 15],
  ["black", 16],
  ["green", "00"],
];
